/**
 * Expo config plugin — certificate pinning
 *
 * iOS:  NSPinnedDomains is injected into Info.plist via app.json infoPlist.
 *       This plugin handles the Android side only.
 *
 * Android: Creates res/xml/network_security_config.xml and sets
 *   android:networkSecurityConfig on the <application> element.
 *
 * ── Before going to production ───────────────────────────────────────────────
 * Replace the SPKI_PINS placeholders below with the real SHA-256 SPKI hashes
 * of your TLS leaf certificates (and one backup / intermediate).
 *
 * To obtain a hash from an existing cert:
 *   openssl x509 -in cert.pem -pubkey -noout \
 *     | openssl pkey -pubin -outform DER \
 *     | openssl dgst -sha256 -binary \
 *     | base64
 *
 * Pin at least two: the current leaf + one backup (next rotation target or CA).
 * Set `expiration` to your next planned cert rotation date.
 * ─────────────────────────────────────────────────────────────────────────────
 */

import {
  type ConfigPlugin,
  withAndroidManifest,
  withDangerousMod,
} from '@expo/config-plugins';
import * as fs from 'fs';
import * as path from 'path';

// ── Pin configuration ─────────────────────────────────────────────────────────

const PINNED_DOMAINS: Array<{
  host:          string;
  includeSubdomains: boolean;
  expiration:    string;     // ISO date — set to cert rotation date
  pins:          string[];   // SHA-256 SPKI hashes in base64
}> = [
  {
    host:              'relay.conduit.app',
    includeSubdomains: false,
    expiration:        '2027-01-01',
    // TODO: replace with real SPKI hashes before production deployment
    pins: [
      'REPLACE_WITH_RELAY_LEAF_SPKI_SHA256_BASE64=',
      'REPLACE_WITH_RELAY_BACKUP_SPKI_SHA256_BASE64=',
    ],
  },
  {
    host:              'api.conduit.app',
    includeSubdomains: false,
    expiration:        '2027-01-01',
    pins: [
      'REPLACE_WITH_API_LEAF_SPKI_SHA256_BASE64=',
      'REPLACE_WITH_API_BACKUP_SPKI_SHA256_BASE64=',
    ],
  },
];

// ── XML builder ───────────────────────────────────────────────────────────────

function buildNetworkSecurityConfig(): string {
  const domainConfigs = PINNED_DOMAINS.map((d) => {
    const pins = d.pins
      .map((p) => `      <pin digest="SHA-256">${p}</pin>`)
      .join('\n');

    return `
  <domain-config cleartextTrafficPermitted="false">
    <domain includeSubdomains="${d.includeSubdomains}">${d.host}</domain>
    <pin-set expiration="${d.expiration}">
${pins}
    </pin-set>
  </domain-config>`;
  }).join('\n');

  return `<?xml version="1.0" encoding="utf-8"?>
<!--
  GENERATED by plugins/withCertificatePinning.ts — do not edit directly.
  Update PINNED_DOMAINS in the plugin source and rebuild.
-->
<network-security-config>
  <!-- Block all cleartext (HTTP) traffic app-wide -->
  <base-config cleartextTrafficPermitted="false">
    <trust-anchors>
      <certificates src="system" />
    </trust-anchors>
  </base-config>
${domainConfigs}
</network-security-config>
`;
}

// ── Plugin ────────────────────────────────────────────────────────────────────

const withCertificatePinning: ConfigPlugin = (config) => {
  // Step 1: write network_security_config.xml
  config = withDangerousMod(config, [
    'android',
    async (cfg) => {
      const xmlDir = path.join(
        cfg.modRequest.platformProjectRoot,
        'app', 'src', 'main', 'res', 'xml',
      );
      fs.mkdirSync(xmlDir, { recursive: true });
      fs.writeFileSync(
        path.join(xmlDir, 'network_security_config.xml'),
        buildNetworkSecurityConfig(),
        'utf8',
      );
      return cfg;
    },
  ]);

  // Step 2: reference it in AndroidManifest <application>
  config = withAndroidManifest(config, (cfg) => {
    const app = cfg.modResults.manifest.application?.[0];
    if (app) {
      app.$['android:networkSecurityConfig'] = '@xml/network_security_config';
    }
    return cfg;
  });

  return config;
};

export default withCertificatePinning;
